### ISSUE TITLE
Sign in with Google/Facebook/Apple logic

### ISSUE THREAD

**Issue by dave-cao** [Firm-Collective/ai-journal#25]
Need testing for IOS

**Comment by Lyton505** [comment]
@dave-cao was your fix for the error "Value being stored in Securestore is larger than 2048 bytes" a permanent fix? I'm getting the same error when logging in with Apple on ios

**Comment by Lyton505** [comment]
Apple sign in requires an Apple developer account. See [here](https://supabase.com/docs/guides/auth/social-login/auth-apple?queryGroups=framework&framework=express&queryGroups=platform&platform=react-native&queryGroups=environment&environment=server#:~:text=When%20developing%20with%20Expo%2C%20you%20can%20test%20Sign%20in%20with%20Apple%20via%20the%20Expo%20Go%20app%2C%20in%20all%20other%20cases%20you%20will%20need%20to%20obtain%20an%20Apple%20Developer%20account%20to%20enable%20the%20capability.) and [here](https://developer.apple.com/documentation/sign_in_with_apple/configuring_your_environment_for_sign_in_with_apple)

**Comment by Lyton505** [comment]
For the secure store error, I've found [this](https://stackoverflow.com/questions/76389249/provided-value-to-securestore-is-larger-than-2048-bytes-while-trying-to-store) and [this](https://supabase.com/docs/guides/getting-started/tutorials/with-expo-react-native?auth-store=secure-store&queryGroups=auth-store#initialize-a-react-native-app)

**Comment by dave-cao** [comment]
> @dave-cao was your fix for the error "Value being stored in Securestore is larger than 2048 bytes" a permanent fix? I'm getting the same error when logging in with Apple on ios

What my fix did was compress the information before storing it, and then when grabbing it again, it would decompress the information. I'm guessing even after compressing it, it still goes over 2048 bytes.

**Comment by dave-cao** [comment]
> For the secure store error, I've found [this](https://stackoverflow.com/questions/76389249/provided-value-to-securestore-is-larger-than-2048-bytes-while-trying-to-store) and [this](https://supabase.com/docs/guides/getting-started/tutorials/with-expo-react-native?auth-store=secure-store&queryGroups=auth-store#initialize-a-react-native-app)

@Lyton505 I tried the first link you send here and it works! What branch are you working from? I can add it in there so we can test it out.

**Comment by Lyton505** [comment]
I'm on fbAuth-dev

**Comment by dave-cao** [comment]
> I'm on fbAuth-dev

@Lyton505 I changed and pushed the new secure store!

**Comment by dave-cao** [comment]
@Lyton505 In the fbAuth-dev branch, I am getting this error when trying to login with Facebook:

![Image](https://github.com/Firm-Collective/ai-journal/assets/63488152/ffe15022-61bf-439f-a7aa-ed76c4030a3c)

![Image](https://github.com/Firm-Collective/ai-journal/assets/63488152/d1eda92c-6544-4f28-8055-ba75180e155c)

**Comment by Lyton505** [comment]
The current implementation should work. @jb2700 can you test FB login and apple login on ios? Apple login works in expo go using face id so I'm interested in how it works on an emulator so please let me know about that as well
