### ISSUE TITLE
Update welcome page with updated designs

### ISSUE THREAD

**Issue by dave-cao** [Firm-Collective/ai-journal#39]
The designers just updated the design to include some smaller text and dots underneath the main title.

- new authentication header image
- new landing page images

Current:
![Image](https://github.com/user-attachments/assets/f7b50252-f3f5-4992-a969-b286c3a07e26)

New:
![Image](https://github.com/user-attachments/assets/62689103-a1d3-4fdb-8c2a-dff1cbe151d5)

Found within the **Ready for Development** figma tab.

Update the back button so it only goes to the landing page for the authentication header.

**Comment by Lyton505** [comment]
what exactly needs to be done here? The scroll animation opens what exactly?

**Comment by dave-cao** [comment]
> what exactly needs to be done here? The scroll animation opens what exactly?

@Lyton505 I updated the description.
