### ISSUE TITLE
Add logic within Supabase when a new account is created, it will create a new authenticated user

### ISSUE THREAD

**Issue by dave-cao** [Firm-Collective/ai-journal#43]
## Description
The basic functionality of this is to have it so when a new user is registered, it will populate within the User table within supabase. We can do this a variety of ways.

1. We can have a function within our react native code where, after a successful signup, it will push user data and user id into the User table
2. Use the SQL query editor and Database triggers (recommended) to automatically add a new user when a new user signs up via Supabase Auth.

The following is what I found for number 2.
![Image](https://github.com/Firm-Collective/ai-journal/assets/63488152/f75b657b-9298-464f-b803-c6fb1b635c04)

Within Supabase, if you go into SQL Editor, there are Quickstarts in which you can use for inspiration.
Link about using triggers: https://supabase.com/docs/guides/auth/managing-user-data#using-triggers

## Checklist
- [ ] When I register a new user, it will show up within the Users table in Supabase automatically
- [ ] the new User will have an id, email, and any other relevant data (maybe even a user profile)

**Comment by Lyton505** [comment]
working on this. can we change supabase tables names to lowercase? This removed the need for quotes in SQL commands. See h[ere](https://github.com/orgs/supabase/discussions/619#discussioncomment-315474)

**Comment by dave-cao** [comment]
> working on this. can we change supabase tables names to lowercase? This removed the need for quotes in SQL commands. See [here](https://github.com/orgs/supabase/discussions/619#discussioncomment-315474)

Yep that's a good idea. I think it's common practice for it to be in lowercase.

**Comment by Lyton505** [comment]
@dave-cao check this in supabase and let me know what you think. Otherwise this issue is settled

**Comment by dave-cao** [comment]
@Lyton505 Tested and is working!
